
import java.io.IOException;
import formatter.Compiler;
import formatter.Formatter;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Code formatter project
 * CS 4481
 */
/**
 *
 * @author Nate
 */
public class GUI extends javax.swing.JFrame {

  public static String sourceCodeLocation;
  public static String sourceCode;

  /**
   * Creates new form NewJFrame
   */
  public GUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtCodePane = new javax.swing.JTextPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtTargetPane = new javax.swing.JTextPane();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    btnOpenFile = new javax.swing.JButton();
    btnSaveFile = new javax.swing.JButton();
    btnCompile = new javax.swing.JButton();
    btnSaveCompiled = new javax.swing.JButton();
    btnFormatCode = new javax.swing.JButton();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jSplitPane1.setDividerLocation(600);

    txtCodePane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jScrollPane1.setViewportView(txtCodePane);

    jSplitPane1.setLeftComponent(jScrollPane1);

    txtTargetPane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jScrollPane2.setViewportView(txtTargetPane);

    jSplitPane1.setRightComponent(jScrollPane2);

    jButton1.setText("jButton1");

    jButton2.setText("jButton2");

    btnOpenFile.setText("Open File");
    btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOpenFileActionPerformed(evt);
      }
    });

    btnSaveFile.setText("Save File");
    btnSaveFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSaveFileActionPerformed(evt);
      }
    });

    btnCompile.setText("Compile");
    btnCompile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCompileActionPerformed(evt);
      }
    });

    btnSaveCompiled.setText("Save Compiled");
    btnSaveCompiled.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSaveCompiledActionPerformed(evt);
      }
    });

    btnFormatCode.setText("Format Code");
    btnFormatCode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFormatCodeActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnOpenFile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnFormatCode)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSaveFile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnCompile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSaveCompiled)
        .addContainerGap(860, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(9, 9, 9)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnOpenFile)
          .addComponent(btnSaveFile)
          .addComponent(btnCompile)
          .addComponent(btnSaveCompiled)
          .addComponent(btnFormatCode))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSplitPane1)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private String readFile(String fileLocation) {
    String text = "";
    try {
      FileReader fr = new FileReader(fileLocation);
      BufferedReader br = new BufferedReader(fr);
      String s;
      while ((s = br.readLine()) != null) {
        text += s + "\n";
      }
      fr.close();
    } catch (FileNotFoundException ex) {
      Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
      Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    return text;
  }

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    sourceCode = readFile(sourceCodeLocation);
    txtCodePane.setText(sourceCode);
  }//GEN-LAST:event_formWindowOpened

  /**
   * Pulls text from a file into the source code pane.
   */
  private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    int result = fileChooser.showOpenDialog(jPanel1);
    if (result == JFileChooser.APPROVE_OPTION) {
      // user selects a file
      File selectedFile = fileChooser.getSelectedFile();
      sourceCodeLocation = selectedFile.getAbsolutePath();
      sourceCode = readFile(sourceCodeLocation);
      txtCodePane.setText(sourceCode);
    }
  }//GEN-LAST:event_btnOpenFileActionPerformed

  private void btnCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompileActionPerformed
    sourceCode = txtCodePane.getText();
    try {
      txtTargetPane.setText(Compiler.getFormatted(sourceCode));
      txtTargetPane.setCaretPosition(0);
    } catch (IOException ex) {
      Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btnCompileActionPerformed

  private void btnSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    FileFilter filter = new FileNameExtensionFilter("Please add .C to this file.", new String[]{"c"});
    fileChooser.setFileFilter(filter);
    fileChooser.addChoosableFileFilter(filter);
    int result = fileChooser.showSaveDialog(jPanel1);
    if (result == JFileChooser.APPROVE_OPTION) {
      // user selects a file
      File selectedFile = fileChooser.getSelectedFile();
      sourceCodeLocation = selectedFile.getAbsolutePath();
      sourceCode = txtCodePane.getText();

      PrintWriter writer;
      try {
        writer = new PrintWriter(sourceCodeLocation);
        writer.append(sourceCode);
        writer.close();
      } catch (FileNotFoundException ex) {
        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

  }//GEN-LAST:event_btnSaveFileActionPerformed

  private void btnSaveCompiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCompiledActionPerformed
    sourceCode = txtCodePane.getText();
    try {
      txtTargetPane.setText(Compiler.getFormatted(sourceCode));
      txtTargetPane.setCaretPosition(0);
    } catch (IOException ex) {
      Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    FileFilter filter = new FileNameExtensionFilter("Please add .ASM to the end of your file.", new String[]{"asm"});
    fileChooser.setFileFilter(filter);
    fileChooser.addChoosableFileFilter(filter);
    int result = fileChooser.showSaveDialog(jPanel1);
    if (result == JFileChooser.APPROVE_OPTION) {
      // user selects a file
      File selectedFile = fileChooser.getSelectedFile();
      String compiledFileLocation = selectedFile.getAbsolutePath();

      PrintWriter writer;
      try {
        writer = new PrintWriter(compiledFileLocation);
        writer.append(txtTargetPane.getText());
        writer.close();
      } catch (FileNotFoundException ex) {
        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }//GEN-LAST:event_btnSaveCompiledActionPerformed

  private void btnFormatCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatCodeActionPerformed
    sourceCode = txtCodePane.getText();
    txtCodePane.setText(Formatter.getFormatted(sourceCode));
    txtCodePane.setCaretPosition(0);
  }//GEN-LAST:event_btnFormatCodeActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) throws IOException {

    if (args[args.length - 1].equals("-g")) {

      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
          if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
          }
        }
      } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>
      sourceCodeLocation = args[0];
      Compiler.main(args);


      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new GUI().setVisible(true);
        }
      });
    } else {
      Compiler.main(args);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCompile;
  private javax.swing.JButton btnFormatCode;
  private javax.swing.JButton btnOpenFile;
  private javax.swing.JButton btnSaveCompiled;
  private javax.swing.JButton btnSaveFile;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTextPane txtCodePane;
  private javax.swing.JTextPane txtTargetPane;
  // End of variables declaration//GEN-END:variables
}
